/**
 * Formelsammlung – alle wichtigen Formeln aus den 5 Modulen
 * Basiert auf PROMPT.md und den Modulinhalten
 */

export interface FormulaEntry {
  id: string;
  name: string;
  module: 'elektrizitaet' | 'schwingungen' | 'quantenobjekte' | 'atomhuelle' | 'messunsicherheiten';
  formula: string;
  variables: Record<string, string>;
  context?: string;
  lessonHref: string;
  level?: 'gA' | 'eA';
  searchTerms: string[];
}

export const formulas: FormulaEntry[] = [
  // --- Elektrizität ---
  {
    id: 'feldstaerke',
    name: 'Elektrische Feldstärke',
    module: 'elektrizitaet',
    formula: 'E = \\frac{F}{q}',
    variables: {
      E: 'Elektrische Feldstärke [N/C = V/m]',
      F: 'Kraft auf Probekörper [N]',
      q: 'Ladung [C]',
    },
    context: 'Definition der elektrischen Feldstärke',
    lessonHref: '/elektrizitaet/elektrisches-feld/feldstaerke-feldlinien',
    searchTerms: ['feldstärke', 'elektrisch', 'kraft', 'ladung', 'e', 'f', 'q'],
  },
  {
    id: 'plattenkondensator-e',
    name: 'Feldstärke im Plattenkondensator',
    module: 'elektrizitaet',
    formula: 'E = \\frac{U}{d}',
    variables: {
      E: 'Elektrische Feldstärke [V/m]',
      U: 'Spannung [V]',
      d: 'Plattenabstand [m]',
    },
    context: 'Homogenes Feld zwischen zwei geladenen Platten',
    lessonHref: '/elektrizitaet/elektrisches-feld/feldstaerke-feldlinien',
    searchTerms: ['kondensator', 'platte', 'feld', 'spannung', 'abstand'],
  },
  {
    id: 'kapazitaet',
    name: 'Kapazität',
    module: 'elektrizitaet',
    formula: 'C = \\frac{Q}{U}',
    variables: {
      C: 'Kapazität [F]',
      Q: 'Ladung [C]',
      U: 'Spannung [V]',
    },
    context: 'Definition der Kapazität eines Kondensators',
    lessonHref: '/elektrizitaet/elektrisches-feld/kondensator-kapazitaet',
    searchTerms: ['kapazität', 'kondensator', 'ladung', 'spannung', 'farad'],
  },
  {
    id: 'energie-elektron',
    name: 'Energiebilanz beschleunigtes Elektron',
    module: 'elektrizitaet',
    formula: '\\frac{1}{2} m v^2 = e \\cdot U_A',
    variables: {
      m: 'Elektronenmasse [kg]',
      v: 'Geschwindigkeit [m/s]',
      e: 'Elementarladung [C]',
      'U_A': 'Beschleunigungsspannung [V]',
    },
    context: 'Kinetic energy gained by electron in electric field',
    lessonHref: '/elektrizitaet/elektrisches-feld/kondensator-kapazitaet',
    searchTerms: ['energie', 'elektron', 'beschleunigung', 'spannung'],
  },
  {
    id: 'entladevorgang',
    name: 'Entladevorgang Kondensator',
    module: 'elektrizitaet',
    formula: 'I(t) = I_0 \\cdot e^{-t/(RC)}',
    variables: {
      'I(t)': 'Stromstärke zur Zeit t [A]',
      I_0: 'Anfangsstromstärke [A]',
      t: 'Zeit [s]',
      R: 'Widerstand [Ω]',
      C: 'Kapazität [F]',
    },
    context: 'Exponentialer Verlauf der Entladung',
    lessonHref: '/elektrizitaet/elektrisches-feld/entladevorgang',
    level: 'eA',
    searchTerms: ['entladung', 'kondensator', 'exponential', 'strom', 'rc'],
  },
  {
    id: 'flussdichte',
    name: 'Magnetische Flussdichte',
    module: 'elektrizitaet',
    formula: 'B = \\frac{F}{I \\cdot s}',
    variables: {
      B: 'Magnetische Flussdichte [T]',
      F: 'Kraft auf Leiter [N]',
      I: 'Stromstärke [A]',
      s: 'Leiterlänge im Feld [m]',
    },
    context: 'Definition der magnetischen Flussdichte (Stromwaage)',
    lessonHref: '/elektrizitaet/magnetisches-feld/flussdichte',
    level: 'eA',
    searchTerms: ['flussdichte', 'magnetisch', 'stromwaage', 'kraft', 'leiter'],
  },
  {
    id: 'lorentzkraft',
    name: 'Lorentzkraft',
    module: 'elektrizitaet',
    formula: 'F_L = q \\cdot v \\cdot B',
    variables: {
      'F_L': 'Lorentzkraft [N]',
      q: 'Ladung [C]',
      v: 'Geschwindigkeit [m/s]',
      B: 'Magnetische Flussdichte [T]',
    },
    context: 'Kraft auf bewegte Ladung im Magnetfeld',
    lessonHref: '/elektrizitaet/magnetisches-feld/lorentzkraft',
    searchTerms: ['lorentz', 'kraft', 'magnetfeld', 'ladung', 'bewegung'],
  },
  {
    id: 'wien-filter',
    name: 'Wien-Filter Geschwindigkeit',
    module: 'elektrizitaet',
    formula: 'v = \\frac{E}{B}',
    variables: {
      v: 'Geschwindigkeit [m/s]',
      E: 'Elektrische Feldstärke [V/m]',
      B: 'Magnetische Flussdichte [T]',
    },
    context: 'Teilchen gleicher Geschwindigkeit passieren Wien-Filter',
    lessonHref: '/elektrizitaet/magnetisches-feld/lorentzkraft',
    level: 'eA',
    searchTerms: ['wien', 'filter', 'geschwindigkeit', 'e', 'b'],
  },
  {
    id: 'em-bestimmung',
    name: 'Spezifische Ladung e/m',
    module: 'elektrizitaet',
    formula: '\\frac{e}{m_e} = \\frac{v}{r \\cdot B}',
    variables: {
      e: 'Elementarladung [C]',
      m_e: 'Elektronenmasse [kg]',
      v: 'Geschwindigkeit [m/s]',
      r: 'Radius der Kreisbahn [m]',
      B: 'Magnetische Flussdichte [T]',
    },
    context: 'Fadenstrahlrohr: Kreisbahn im Magnetfeld',
    lessonHref: '/elektrizitaet/magnetisches-feld/em-bestimmung',
    level: 'eA',
    searchTerms: ['spezifisch', 'ladung', 'elektron', 'fadenstrahlrohr', 'kreisbahn'],
  },
  {
    id: 'hallspannung',
    name: 'Hallspannung',
    module: 'elektrizitaet',
    formula: 'U_H = R_H \\cdot \\frac{I \\cdot B}{d}',
    variables: {
      'U_H': 'Hallspannung [V]',
      'R_H': 'Hall-Konstante = 1/(n·e) [m³/C]',
      I: 'Stromstärke [A]',
      B: 'Magnetische Flussdichte [T]',
      d: 'Dicke des Leiters [m]',
    },
    context: 'Hall-Effekt: Querspannung im stromdurchflossenen Leiter',
    lessonHref: '/elektrizitaet/magnetisches-feld/hallspannung',
    level: 'eA',
    searchTerms: ['hall', 'spannung', 'hall-effekt', 'ladungsträger'],
  },
  {
    id: 'induktionsgesetz',
    name: 'Induktionsgesetz',
    module: 'elektrizitaet',
    formula: 'U_{ind} = -N \\cdot \\frac{\\Delta \\Phi}{\\Delta t}',
    variables: {
      'U_{ind}': 'Induzierte Spannung [V]',
      N: 'Windungszahl',
      '\\Phi': 'Magnetischer Fluss [Wb]',
      t: 'Zeit [s]',
    },
    context: 'Differenzielles Induktionsgesetz',
    lessonHref: '/elektrizitaet/magnetisches-feld/induktionsgesetz',
    level: 'eA',
    searchTerms: ['induktion', 'spannung', 'fluss', 'faraday', 'magnetfeld'],
  },
  // --- Schwingungen & Wellen ---
  {
    id: 'harmonisch',
    name: 'Harmonische Schwingung',
    module: 'schwingungen',
    formula: 'y(t) = y_{max} \\cdot \\sin(\\omega \\cdot t)',
    variables: {
      'y(t)': 'Auslenkung zur Zeit t [m]',
      'y_{max}': 'Amplitude [m]',
      '\\omega': 'Kreisfrequenz [1/s]',
      t: 'Zeit [s]',
    },
    context: 'Grundgrößen harmonischer Schwingungen',
    lessonHref: '/schwingungen/harmonische-schwingungen/grundgroessen',
    searchTerms: ['harmonisch', 'schwingung', 'sinus', 'amplitude', 'auslenkung'],
  },
  {
    id: 'kreisfrequenz',
    name: 'Kreisfrequenz und Frequenz',
    module: 'schwingungen',
    formula: 'f = \\frac{1}{T} \\quad,\\quad \\omega = 2\\pi f',
    variables: {
      f: 'Frequenz [Hz]',
      T: 'Periodendauer [s]',
      '\\omega': 'Kreisfrequenz [1/s]',
    },
    context: 'Zusammenhang Frequenz und Periodendauer',
    lessonHref: '/schwingungen/harmonische-schwingungen/grundgroessen',
    searchTerms: ['frequenz', 'periode', 'kreisfrequenz', 'omega'],
  },
  {
    id: 'feder-masse',
    name: 'Periodendauer Feder-Masse-Pendel',
    module: 'schwingungen',
    formula: 'T = 2\\pi \\sqrt{\\frac{m}{D}}',
    variables: {
      T: 'Periodendauer [s]',
      m: 'Masse [kg]',
      D: 'Federkonstante [N/m]',
    },
    context: 'Thomson-Gleichung für Feder-Masse-System',
    lessonHref: '/schwingungen/harmonische-schwingungen/feder-masse',
    searchTerms: ['feder', 'masse', 'pendel', 'periodendauer', 'schwingung'],
  },
  {
    id: 'rückstellkraft',
    name: 'Lineares Kraftgesetz (Rückstellkraft)',
    module: 'schwingungen',
    formula: 'F = -D \\cdot x',
    variables: {
      F: 'Rückstellkraft [N]',
      D: 'Federkonstante [N/m]',
      x: 'Auslenkung [m]',
    },
    context: 'Hookesches Gesetz für harmonische Schwingung',
    lessonHref: '/schwingungen/harmonische-schwingungen/feder-masse',
    searchTerms: ['rückstellkraft', 'feder', 'hooke', 'auslenkung'],
  },
  {
    id: 'wellengleichung',
    name: 'Wellenausbreitung',
    module: 'schwingungen',
    formula: 'c = \\lambda \\cdot f',
    variables: {
      c: 'Ausbreitungsgeschwindigkeit [m/s]',
      '\\lambda': 'Wellenlänge [m]',
      f: 'Frequenz [Hz]',
    },
    context: 'Zusammenhang Wellenlänge, Frequenz und Phasengeschwindigkeit',
    lessonHref: '/schwingungen/wellen-interferenz/wellenausbreitung',
    searchTerms: ['welle', 'wellenlänge', 'frequenz', 'geschwindigkeit', 'lambda'],
  },
  {
    id: 'doppelspalt-max',
    name: 'Doppelspalt – Maxima',
    module: 'schwingungen',
    formula: '\\Delta s = n \\cdot \\lambda \\quad (n = 0, 1, 2, \\ldots)',
    variables: {
      '\\Delta s': 'Gangunterschied [m]',
      n: 'Ordnung des Maximums',
      '\\lambda': 'Wellenlänge [m]',
    },
    context: 'Bedingung für konstruktive Interferenz am Doppelspalt',
    lessonHref: '/schwingungen/wellen-interferenz/interferenz',
    searchTerms: ['doppelspalt', 'interferenz', 'maximum', 'gangunterschied'],
  },
  {
    id: 'doppelspalt-min',
    name: 'Doppelspalt – Minima',
    module: 'schwingungen',
    formula: '\\Delta s = \\left(n - \\frac{1}{2}\\right) \\cdot \\lambda',
    variables: {
      '\\Delta s': 'Gangunterschied [m]',
      n: 'Ordnung',
      '\\lambda': 'Wellenlänge [m]',
    },
    context: 'Bedingung für destruktive Interferenz',
    lessonHref: '/schwingungen/wellen-interferenz/interferenz',
    searchTerms: ['doppelspalt', 'interferenz', 'minimum', 'auslöschung'],
  },
  {
    id: 'gitter',
    name: 'Gittergleichung',
    module: 'schwingungen',
    formula: '\\sin(\\alpha_n) = \\frac{\\Delta s}{g}',
    variables: {
      '\\alpha_n': 'Winkel der n-ten Beugungsordnung',
      '\\Delta s': 'Gangunterschied [m]',
      g: 'Gitterkonstante [m]',
    },
    context: 'Beugung am Gitter',
    lessonHref: '/schwingungen/wellen-interferenz/gitter-bragg',
    level: 'eA',
    searchTerms: ['gitter', 'beugung', 'winkel', 'ordnung'],
  },
  {
    id: 'bragg',
    name: 'Bragg-Bedingung',
    module: 'schwingungen',
    formula: 'n \\cdot \\lambda = 2d \\cdot \\sin(\\theta_n)',
    variables: {
      n: 'Ordnung',
      '\\lambda': 'Wellenlänge [m]',
      d: 'Netzebenenabstand [m]',
      '\\theta_n': 'Glanzwinkel',
    },
    context: 'Bragg-Reflexion, Röntgenstrukturanalyse',
    lessonHref: '/schwingungen/wellen-interferenz/gitter-bragg',
    level: 'eA',
    searchTerms: ['bragg', 'reflexion', 'röntgen', 'kristall', 'netzebene'],
  },
  // --- Quantenobjekte ---
  {
    id: 'photoeffekt',
    name: 'Photoeffekt – Einstein',
    module: 'quantenobjekte',
    formula: 'e \\cdot U_s = h \\cdot f',
    variables: {
      e: 'Elementarladung [C]',
      'U_s': 'Sperrspannung [V]',
      h: 'Plancksches Wirkungsquantum [J·s]',
      f: 'Frequenz des Lichts [Hz]',
    },
    context: 'Energie des Photons und kinetische Energie des Elektrons',
    lessonHref: '/quantenobjekte/quantenphysik/photoeffekt',
    searchTerms: ['photoeffekt', 'einstein', 'planck', 'sperrspannung', 'photon'],
  },
  {
    id: 'roentgen-grenze',
    name: 'Röntgenbremsspektrum – Grenzwellenlänge',
    module: 'quantenobjekte',
    formula: 'E = e \\cdot U_A = h \\cdot f_{max} = \\frac{hc}{\\lambda_{min}}',
    variables: {
      E: 'Maximale Photonenenergie [J]',
      e: 'Elementarladung [C]',
      'U_A': 'Beschleunigungsspannung [V]',
      h: 'Plancksches Wirkungsquantum [J·s]',
      'f_{max}': 'Maximale Frequenz [Hz]',
      c: 'Lichtgeschwindigkeit [m/s]',
      '\\lambda_{min}': 'Kurzwellengrenze [m]',
    },
    context: 'Vollständige Umwandlung der Elektronenenergie in Photonenenergie',
    lessonHref: '/quantenobjekte/quantenphysik/roentgen',
    level: 'eA',
    searchTerms: ['röntgen', 'bremsspektrum', 'grenze', 'wellenlänge', 'energie'],
  },
  {
    id: 'debroglie',
    name: 'de-Broglie-Wellenlänge',
    module: 'quantenobjekte',
    formula: '\\lambda = \\frac{h}{p} = \\frac{h}{m \\cdot v}',
    variables: {
      '\\lambda': 'Wellenlänge [m]',
      h: 'Plancksches Wirkungsquantum [J·s]',
      p: 'Impuls [kg·m/s]',
      m: 'Masse [kg]',
      v: 'Geschwindigkeit [m/s]',
    },
    context: 'Materiewelle, Wellenlänge eines Teilchens',
    lessonHref: '/quantenobjekte/quantenphysik/debroglie',
    searchTerms: ['de-broglie', 'materiewelle', 'wellenlänge', 'impuls', 'elektron'],
  },
  {
    id: 'unschaerfe',
    name: 'Unschärferelation Ort-Impuls',
    module: 'quantenobjekte',
    formula: '\\Delta x \\cdot \\Delta p \\geq \\frac{h}{4\\pi}',
    variables: {
      '\\Delta x': 'Ortsunschärfe [m]',
      '\\Delta p': 'Impulsunschärfe [kg·m/s]',
      h: 'Plancksches Wirkungsquantum [J·s]',
    },
    context: 'Heisenbergsche Unschärferelation',
    lessonHref: '/quantenobjekte/quantenphysik/unschaerferelation',
    level: 'eA',
    searchTerms: ['unschärfe', 'heisenberg', 'ort', 'impuls', 'quanten'],
  },
  // --- Atomhülle & Atomkern ---
  {
    id: 'potenzialtopf',
    name: 'Energie im Potenzialtopf',
    module: 'atomhuelle',
    formula: 'E_n = \\frac{h^2}{8 \\cdot m_e \\cdot L^2} \\cdot n^2',
    variables: {
      'E_n': 'Energie des n-ten Zustands [J]',
      h: 'Plancksches Wirkungsquantum [J·s]',
      m_e: 'Elektronenmasse [kg]',
      L: 'Breite des Topfs [m]',
      n: 'Quantenzahl (1, 2, 3, …)',
    },
    context: 'Eindimensionaler Potenzialtopf: diskrete Energieniveaus',
    lessonHref: '/atomhuelle/atomhuelle-kapitel/potenzialtopf',
    level: 'eA',
    searchTerms: ['potenzialtopf', 'energie', 'quantenzahl', 'elektron'],
  },
  {
    id: 'energieuebergang',
    name: 'Energieübergang Atomhülle',
    module: 'atomhuelle',
    formula: '\\Delta E = E_m - E_n = h \\cdot f_{mn}',
    variables: {
      '\\Delta E': 'Energiedifferenz [J]',
      'E_m, E_n': 'Energieniveaus [J]',
      h: 'Plancksches Wirkungsquantum [J·s]',
      'f_{mn}': 'Frequenz des Photons [Hz]',
    },
    context: 'Emission und Absorption von Photonen',
    lessonHref: '/atomhuelle/atomhuelle-kapitel/linienspektren',
    searchTerms: ['energieübergang', 'emission', 'absorption', 'photon', 'linie'],
  },
  {
    id: 'balmer',
    name: 'Balmerformel',
    module: 'atomhuelle',
    formula: 'f = R \\cdot \\left(\\frac{1}{2^2} - \\frac{1}{m^2}\\right) \\quad (m = 3, 4, 5, \\ldots)',
    variables: {
      f: 'Frequenz [Hz]',
      R: 'Rydberg-Konstante [Hz]',
      m: 'Obere Quantenzahl',
    },
    context: 'Wasserstoff-Spektrum, Balmer-Serie',
    lessonHref: '/atomhuelle/atomhuelle-kapitel/linienspektren',
    searchTerms: ['balmer', 'wasserstoff', 'spektrum', 'rydberg', 'serie'],
  },
  {
    id: 'zerfallsgesetz',
    name: 'Zerfallsgesetz',
    module: 'atomhuelle',
    formula: 'N(t) = N_0 \\cdot e^{-\\lambda t}',
    variables: {
      'N(t)': 'Anzahl der Kerne zur Zeit t',
      'N_0': 'Anfangszahl der Kerne',
      '\\lambda': 'Zerfallskonstante [1/s]',
      t: 'Zeit [s]',
    },
    context: 'Exponentieller radioaktiver Zerfall',
    lessonHref: '/atomhuelle/atomkern/zerfallsgesetz',
    searchTerms: ['zerfall', 'radioaktiv', 'exponential', 'kerne', 'lambda'],
  },
  {
    id: 'halbwertszeit',
    name: 'Halbwertszeit',
    module: 'atomhuelle',
    formula: 'N(t) = N_0 \\cdot \\left(\\frac{1}{2}\\right)^{t/T_{1/2}}',
    variables: {
      'N(t)': 'Anzahl der Kerne zur Zeit t',
      'N_0': 'Anfangszahl',
      'T_{1/2}': 'Halbwertszeit [s]',
      t: 'Zeit [s]',
    },
    context: 'Alternative Darstellung mit Halbwertszeit',
    lessonHref: '/atomhuelle/atomkern/zerfallsgesetz',
    searchTerms: ['halbwertszeit', 'zerfall', 't halbe', 'radioaktiv'],
  },
  {
    id: 'zerfallskonstante',
    name: 'Zerfallskonstante und Halbwertszeit',
    module: 'atomhuelle',
    formula: 'T_{1/2} = \\frac{\\ln(2)}{\\lambda}',
    variables: {
      'T_{1/2}': 'Halbwertszeit [s]',
      '\\lambda': 'Zerfallskonstante [1/s]',
    },
    context: 'Zusammenhang zwischen T½ und λ',
    lessonHref: '/atomhuelle/atomkern/zerfallsgesetz',
    searchTerms: ['halbwertszeit', 'zerfallskonstante', 'lambda', 'ln'],
  },
  // --- Messunsicherheiten ---
  {
    id: 'relative-unsicherheit',
    name: 'Relative Unsicherheit',
    module: 'messunsicherheiten',
    formula: '\\frac{\\Delta x}{x}',
    variables: {
      '\\Delta x': 'Absolute Unsicherheit',
      x: 'Messwert',
    },
    context: 'Dimensionslose relative Unsicherheit (oft in %)',
    lessonHref: '/messunsicherheiten/messunsicherheiten-kapitel/absolute-relative',
    level: 'eA',
    searchTerms: ['unsicherheit', 'relativ', 'messung', 'fehler'],
  },
  {
    id: 'fehlerfortpflanzung',
    name: 'Schwächstes Glied',
    module: 'messunsicherheiten',
    formula: '\\frac{\\Delta y}{y} \\geq \\max\\left(\\frac{\\Delta x_1}{x_1}, \\frac{\\Delta x_2}{x_2}, \\ldots\\right)',
    variables: {
      '\\Delta y': 'Unsicherheit des Ergebnisses',
      y: 'Ergebnis',
      '\\Delta x_i': 'Unsicherheit der Eingangsgröße i',
      'x_i': 'Eingangsgröße i',
    },
    context: 'Größte relative Unsicherheit bestimmt die Gesamtunsicherheit',
    lessonHref: '/messunsicherheiten/messunsicherheiten-kapitel/zusammengesetzte-groessen',
    level: 'eA',
    searchTerms: ['fehlerfortpflanzung', 'unsicherheit', 'zusammengesetzt', 'schwächstes glied'],
  },
];

export const MODULE_LABELS: Record<string, string> = {
  elektrizitaet: 'Elektrizität',
  schwingungen: 'Schwingungen & Wellen',
  quantenobjekte: 'Quantenobjekte',
  atomhuelle: 'Atomhülle & Atomkern',
  messunsicherheiten: 'Messunsicherheiten',
};

export const MODULE_COLORS: Record<string, string> = {
  elektrizitaet: '#4f9cf9',
  schwingungen: '#ff7a5c',
  quantenobjekte: '#b16fff',
  atomhuelle: '#3ecf8e',
  messunsicherheiten: '#ffd166',
};
