import type { QuizQuestion } from '@/lib/types';

type QuizKey = string;

const quizQuestionsMap: Record<QuizKey, QuizQuestion[]> = {
  // ========== MODUL 1: ELEKTRIZITÄT ==========
  'elektrizitaet/elektrisches-feld': [
    {
      id: 'eq1',
      type: 'numeric',
      question: 'Ein Plattenkondensator hat Plattenabstand d = 2 cm und Spannung U = 400 V. Berechne die Feldstärke E.',
      answer: 20000,
      unit: 'V/m',
      tolerance: 0.05,
      hint: '$E = U/d$',
      solution: '$E = 400\\,\\text{V} / 0{,}02\\,\\text{m} = 20.000\\,\\text{V}/\\text{m}$',
      explanation: 'Es gilt $E = U/d$. Der Plattenabstand muss in Metern eingesetzt werden.',
    },
    {
      id: 'eq2',
      type: 'numeric',
      question: 'Ein Kondensator (C = 100 μF) wird mit U = 12 V geladen. Welche Ladung Q speichert er?',
      answer: 1.2,
      unit: 'mC',
      tolerance: 0.05,
      hint: '$Q = C \\cdot U$',
      solution: '$Q = 100 \\cdot 10^{-6}\\,\\text{F} \\cdot 12\\,\\text{V} = 1{,}2\\,\\text{mC}$',
      explanation: '$Q = C \\cdot U$. Die Kapazität in Farad: $100\\,\\mu\\text{F} = 100 \\cdot 10^{-6}\\,\\text{F}$.',
    },
    {
      id: 'eq3',
      type: 'formula-select',
      question: 'Wie lautet die elektrische Feldstärke im Plattenkondensator?',
      options: ['$E = U/d$', '$E = U \\cdot d$', '$E = Q/U$', '$E = F \\cdot q$'],
      correct: 0,
      explanation: 'Im homogenen Feld des Plattenkondensators gilt $E = U/d$.',
    },
    {
      id: 'eq4',
      type: 'formula-select',
      question: 'Wie lautet die Kapazitätsdefinition?',
      options: ['$C = Q \\cdot U$', '$C = Q/U$', '$C = U/Q$', '$C = F/q$'],
      correct: 1,
      explanation: 'Die Kapazität ist $C = Q/U$. Einheit: Farad (F) = C/V.',
    },
    {
      id: 'eq5',
      type: 'multiple-choice',
      question: 'Was beschreibt die Zeitkonstante $\\tau = R \\cdot C$ beim Kondensatorentladevorgang physikalisch?',
      options: ['Die Zeit bis zur vollständigen Entladung', 'Die Zeit, nach der Strom/Spannung auf 37 % gefallen sind', 'Die Halbwertszeit', 'Die Periodendauer'],
      correct: 1,
      explanation: 'Nach $t = \\tau$ ist der Wert auf $e^{-1} \\approx 37\\,\\%$ des Anfangswerts abgefallen.',
    },
    {
      id: 'eq6',
      type: 'formula-select',
      question: 'Wie lautet der Entladestrom I(t) beim Kondensator?',
      options: ['$I(t) = I_0 \\cdot e^{-t/(RC)}$', '$I(t) = I_0 \\cdot t/(RC)$', '$I(t) = I_0 \\cdot (1 - t/(RC))$', '$I(t) = I_0 \\cdot \\sin(t/(RC))$'],
      correct: 0,
      explanation: 'Der Entladestrom nimmt exponentiell ab: $I(t) = I_0 \\cdot e^{-t/\\tau}$ mit $\\tau = R \\cdot C$.',
    },
    {
      id: 'eq7',
      type: 'multiple-choice',
      question: 'Warum verläuft die Entladekurve des Kondensators exponentiell?',
      options: ['Wegen der konstanten Spannung', 'Weil $\\mathrm{d}I/\\mathrm{d}t \\propto -I$ (Differentialgleichung)', 'Wegen des Widerstands', 'Weil die Ladung konstant ist'],
      correct: 1,
      explanation: 'Aus $U_C = Q/C$ und $I = -\\mathrm{d}Q/\\mathrm{d}t$ folgt $\\mathrm{d}Q/\\mathrm{d}t = -Q/(RC)$. Die Lösung ist $Q(t) = Q_0 \\cdot e^{-t/\\tau}$.',
    },
    {
      id: 'eq8',
      type: 'drag-drop',
      question: 'Ordne die Größen ihren Definitionen zu.',
      items: ['$E = F/q$', '$C = Q/U$', '$E = U/d$', '$\\tau = R \\cdot C$'],
      targets: ['Elektrische Feldstärke', 'Kapazität', 'Feldstärke im Plattenkondensator', 'Zeitkonstante bei Entladung'],
      correctPairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: '$E = F/q$ (allgemein), $C = Q/U$ (Kapazität), $E = U/d$ (Plattenkondensator), $\\tau = R \\cdot C$ (Entladung).',
    },
  ],
  'elektrizitaet/magnetisches-feld': [
    {
      id: 'emf1',
      type: 'numeric',
      question: 'Ein Elektron wird durch $U_A = 500\\,\\text{V}$ beschleunigt. Berechne die Geschwindigkeit $v$ (gerundet).',
      answer: 1.33e7,
      unit: 'm/s',
      tolerance: 0.1,
      hint: '$\\frac{1}{2}m_e v^2 = e \\cdot U_A$',
      solution: '$v = \\sqrt{2eU_A/m_e} \\approx 1{,}33 \\cdot 10^7\\,\\text{m}/\\text{s}$',
      explanation: 'Aus $\\frac{1}{2}m_e v^2 = e \\cdot U_A$ folgt $v = \\sqrt{2 \\cdot 1{,}76 \\cdot 10^{11} \\cdot 500} \\approx 1{,}33 \\cdot 10^7\\,\\text{m}/\\text{s}$.',
    },
    {
      id: 'emf2',
      type: 'multiple-choice',
      question: 'Die spezifische Ladung e/m_e des Elektrons beträgt etwa:',
      options: ['$1{,}76 \\cdot 10^{11}\\,\\text{C}/\\text{kg}$', '$1{,}6 \\cdot 10^{-19}\\,\\text{C}/\\text{kg}$', '$9{,}1 \\cdot 10^{-31}\\,\\text{C}/\\text{kg}$', '$1{,}76 \\cdot 10^{10}\\,\\text{C}/\\text{kg}$'],
      correct: 0,
      explanation: '$e/m_e \\approx 1{,}76 \\cdot 10^{11}\\,\\text{C}/\\text{kg}$. Daraus folgt $m_e \\approx 9{,}1 \\cdot 10^{-31}\\,\\text{kg}$.',
    },
    {
      id: 'emf3',
      type: 'formula-select',
      question: 'Wie lautet die Lorentzkraft auf ein geladenes Teilchen (senkrecht zu B)?',
      options: ['$F = q \\cdot v \\cdot B$', '$F = q \\cdot E$', '$F = v \\cdot B/q$', '$F = q/(v \\cdot B)$'],
      correct: 0,
      explanation: 'Die Lorentzkraft ist $F = q \\cdot v \\cdot B$ (bei senkrechter Bewegung zu $B$).',
    },
    {
      id: 'emf4',
      type: 'multiple-choice',
      question: 'Lorentzkraft-Richtung: B zeigt in z-Richtung, v in x-Richtung. In welche Richtung zeigt F?',
      options: ['x-Richtung', 'y-Richtung', 'z-Richtung', '−x-Richtung'],
      correct: 1,
      explanation: '$F = q \\cdot (v \\times B)$. Kreuzprodukt: $x \\times z = -y$ (bzw. $y$ je nach Orientierung). $F$ steht senkrecht auf $v$ und $B$.',
    },
    {
      id: 'emf5',
      type: 'multiple-choice',
      question: 'Warum wird beim Wien-Filter v = E/B für alle Teilchen gleicher Geschwindigkeit erreicht?',
      options: ['Wegen der Masse', 'E- und B-Kraft heben sich bei v = E/B gegenseitig auf', 'Wegen der Ladung', 'Wegen der Temperatur'],
      correct: 1,
      explanation: 'Bei $v = E/B$ sind elektrische und magnetische Kraft gleich groß und entgegengesetzt.',
    },
    {
      id: 'emf6',
      type: 'multiple-choice',
      question: 'Was ist die Hall-Spannung und wovon hängt sie ab?',
      options: ['Spannung am Kondensator; hängt von C ab', 'Querspannung im Leiter; von I, B, n und d abhängig', 'Anodenspannung; von U_A abhängig', 'Sperrspannung; von Lichtfrequenz abhängig'],
      correct: 1,
      explanation: '$U_H = R_H \\cdot (I \\cdot B)/d$ mit $R_H = 1/(n \\cdot e)$. Hängt von Strom, Magnetfeld, Ladungsträgerdichte und Dicke ab.',
    },
    {
      id: 'emf7',
      type: 'multiple-choice',
      question: 'Induktionsgesetz: Was bewirkt das negative Vorzeichen in $U_{ind} = -N \\cdot \\Delta\\Phi/\\Delta t$?',
      options: ['Es ist Konvention', 'Der Induktionsstrom wirkt seiner Ursache entgegen (Lenzsche Regel)', 'Es bedeutet Abnahme der Spannung', 'Es hat keine Bedeutung'],
      correct: 1,
      explanation: 'Die Lenzsche Regel: Der Induktionsstrom ist so gerichtet, dass er der Ursache der Induktion entgegenwirkt.',
    },
    {
      id: 'emf8',
      type: 'drag-drop',
      question: 'Ordne die Formeln den magnetischen Phänomenen zu.',
      items: ['$F = q \\cdot v \\cdot B$', '$U_H = R_H \\cdot (I \\cdot B)/d$', '$U_{ind} = -N \\cdot \\Delta\\Phi/\\Delta t$', '$B = F/(I \\cdot s)$'],
      targets: ['Lorentzkraft', 'Hallspannung', 'Induktionsspannung', 'Flussdichte (Definition)'],
      correctPairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Lorentzkraft, Hallspannung, Induktion und Flussdichte-Definition.',
    },
  ],

  // ========== MODUL 2: SCHWINGUNGEN & WELLEN ==========
  'schwingungen/harmonische-schwingungen': [
    {
      id: 'sq1',
      type: 'multiple-choice',
      question: 'T verdoppelt sich beim Feder-Masse-Pendel, wenn m auf das _-fache zunimmt.',
      options: ['2-fache', '4-fache', '√2-fache', '8-fache'],
      correct: 1,
      explanation: 'Da $T \\propto \\sqrt{m}$, führt $m \\to 4m$ zu $T \\to 2T$.',
    },
    {
      id: 'sq2',
      type: 'numeric',
      question: 'Berechne T für m = 0,5 kg und D = 8 N/m.',
      answer: 1.57,
      unit: 's',
      tolerance: 0.05,
      hint: '$T = 2\\pi \\cdot \\sqrt{m/D}$',
      solution: '$T = 2\\pi \\cdot \\sqrt{0{,}5/8} \\approx 1{,}57\\,\\text{s}$',
      explanation: '$T = 2\\pi \\cdot \\sqrt{m/D} = 2\\pi \\cdot \\sqrt{0{,}5/8} \\approx 1{,}57\\,\\text{s}$.',
    },
    {
      id: 'sq3',
      type: 'formula-select',
      question: 'Was entspricht der Federkonstante D im LC-Schwingkreis?',
      options: ['Induktivität L', 'Kapazität C', 'Kehrwert 1/C', 'Widerstand R'],
      correct: 2,
      explanation: 'Im Schwingkreis entspricht $1/C$ der Federkonstante $D$. Es gilt die Analogie $D \\leftrightarrow 1/C$, $m \\leftrightarrow L$.',
    },
    {
      id: 'sq4',
      type: 'multiple-choice',
      question: 'Bei Resonanz erzwungener Schwingungen gilt:',
      options: ['Die Amplitude ist minimal', 'Erregerfrequenz = Eigenfrequenz', 'Es gibt keine Dämpfung', 'Die Phase ist 0°'],
      correct: 1,
      explanation: 'Bei Resonanz stimmt die Erregerfrequenz mit der Eigenfrequenz überein → maximale Amplitude.',
    },
    {
      id: 'sq5',
      type: 'formula-select',
      question: 'Wie lautet die Thomson-Schwingungsgleichung für den Schwingkreis?',
      options: ['$f = 2\\pi \\cdot \\sqrt{LC}$', '$f = 1/(2\\pi \\cdot \\sqrt{LC})$', '$f = \\sqrt{L \\cdot C}$', '$f = 1/(L \\cdot C)$'],
      correct: 1,
      explanation: 'Die Eigenfrequenz ist $f = 1/(2\\pi \\cdot \\sqrt{LC})$.',
    },
    {
      id: 'sq6',
      type: 'drag-drop',
      question: 'Ordne die Analogiegrößen im LC-Schwingkreis zu.',
      items: ['Induktivität $L$', 'Kehrwert $1/C$', 'Spannung $U_C$', 'Strom $I$'],
      targets: ['Masse $m$', 'Federkonstante $D$', 'Auslenkung $x$', 'Geschwindigkeit $v$'],
      correctPairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: '$L \\leftrightarrow m$, $1/C \\leftrightarrow D$, $U_C \\leftrightarrow x$, $I \\leftrightarrow v$.',
    },
    {
      id: 'sq7',
      type: 'formula-select',
      question: 'Wie lautet die Gleichung für die Periodendauer des Feder-Masse-Pendels?',
      options: ['$T = 2\\pi \\cdot \\sqrt{m/D}$', '$T = 2\\pi \\cdot \\sqrt{D/m}$', '$T = \\sqrt{m/D}$', '$T = 2\\pi \\cdot m \\cdot D$'],
      correct: 0,
      explanation: '$T = 2\\pi \\cdot \\sqrt{m/D}$. Je größer die Masse, desto länger die Periode.',
    },
    {
      id: 'sq8',
      type: 'sort',
      question: 'Ordne die Schwingkreis-Phasen (Beginn: Kondensator geladen).',
      items: ['Kondensator leer, Spule maximal', 'Kondensator geladen, Spule leer', 'Kondensator lädt sich umgekehrt'],
      correctOrder: [1, 0, 2],
      explanation: 'Start geladen → Entladung über Spule → Spule max → Kondensator lädt umgekehrt.',
    },
  ],
  'schwingungen/wellen-interferenz': [
    {
      id: 'sw1',
      type: 'formula-select',
      question: 'Welcher Gangunterschied führt zu einem Maximum am Doppelspalt?',
      options: ['$\\Delta s = (n-1/2) \\cdot \\lambda$', '$\\Delta s = n \\cdot \\lambda$', '$\\Delta s = \\lambda/n$', '$\\Delta s = n/\\lambda$'],
      correct: 1,
      explanation: 'Konstruktive Interferenz (Maximum) bei $\\Delta s = n \\cdot \\lambda$.',
    },
    {
      id: 'sw2',
      type: 'formula-select',
      question: 'Welcher Zusammenhang gilt zwischen c, λ und f?',
      options: ['$c = \\lambda \\cdot f$', '$c = \\lambda/f$', '$c = \\lambda + f$', '$c = f/\\lambda$'],
      correct: 0,
      explanation: 'Es gilt $c = \\lambda \\cdot f$. Die Welle legt in einer Periodendauer genau eine Wellenlänge zurück.',
    },
    {
      id: 'sw3',
      type: 'numeric',
      question: 'Berechne λ für f = 440 Hz und c = 340 m/s.',
      answer: 0.773,
      unit: 'm',
      tolerance: 0.05,
      hint: '$c = \\lambda \\cdot f$',
      solution: '$\\lambda = c/f = 340/440 \\approx 0{,}773\\,\\text{m}$',
      explanation: '$\\lambda = c/f = 340\\,\\text{m}/\\text{s} / 440\\,\\text{Hz} \\approx 0{,}773\\,\\text{m}$.',
    },
    {
      id: 'sw4',
      type: 'multiple-choice',
      question: 'Welche Wellen können polarisiert werden?',
      options: ['Nur Longitudinalwellen', 'Nur Transversalwellen', 'Beide', 'Weder noch'],
      correct: 1,
      explanation: 'Nur Transversalwellen haben eine Schwingungsrichtung und können polarisiert werden.',
    },
    {
      id: 'sw5',
      type: 'multiple-choice',
      question: 'Was ist Schwebung und wie entsteht sie?',
      options: ['Stehende Welle', 'Überlagerung zweier Wellen mit leicht unterschiedlicher Frequenz', 'Reflexion', 'Doppelspalt-Interferenz'],
      correct: 1,
      explanation: 'Schwebung entsteht bei Überlagerung zweier Wellen mit $f_1$ und $f_2$. Schwebungsfrequenz: $|f_1 - f_2|$.',
    },
    {
      id: 'sw6',
      type: 'formula-select',
      question: 'Wie lautet die Bragg-Bedingung für konstruktive Interferenz?',
      options: ['$n \\cdot \\lambda = d \\cdot \\sin(\\theta)$', '$n \\cdot \\lambda = 2d \\cdot \\sin(\\theta)$', '$\\lambda = 2nd \\cdot \\sin(\\theta)$', '$n \\cdot \\lambda = d/\\cos(\\theta)$'],
      correct: 1,
      explanation: 'Die Bragg-Bedingung lautet $n \\cdot \\lambda = 2d \\cdot \\sin(\\theta_n)$. $d$ = Netzebenenabstand, $\\theta$ = Glanzwinkel.',
    },
    {
      id: 'sw7',
      type: 'multiple-choice',
      question: 'Warum können Longitudinalwellen nicht polarisiert werden?',
      options: ['Sie haben keine Frequenz', 'Die Schwingung erfolgt in Ausbreitungsrichtung — keine bevorzugte Ebene', 'Sie sind zu schnell', 'Sie haben keine Amplitude'],
      correct: 1,
      explanation: 'Bei Longitudinalwellen schwingt in Ausbreitungsrichtung. Es gibt keine senkrechte Ebene zur Zuordnung.',
    },
    {
      id: 'sw8',
      type: 'drag-drop',
      question: 'Ordne die Interferenz-Phänomene ihren Bedingungen zu.',
      items: ['$\\Delta s = n \\cdot \\lambda$', '$\\Delta s = (n-1/2) \\cdot \\lambda$', '$|f_1 - f_2|$', '$n \\cdot \\lambda = 2d \\cdot \\sin(\\theta)$'],
      targets: ['Maximum (Doppelspalt)', 'Minimum (Doppelspalt)', 'Schwebungsfrequenz', 'Bragg-Reflexion'],
      correctPairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Maximum, Minimum, Schwebung, Bragg.',
    },
  ],

  // ========== MODUL 3: QUANTENOBJEKTE ==========
  'quantenobjekte/quantenphysik': [
    {
      id: 'qq1',
      type: 'multiple-choice',
      question: 'Welche Messung belegt die Quantennatur des Lichts beim Photoeffekt?',
      options: ['Die Intensität beeinflusst die maximale kinetische Energie', 'Die maximale kinetische Energie hängt von der Frequenz ab, nicht von der Intensität', 'Elektronen werden immer ausgelöst', 'Die Spannung hat keinen Einfluss'],
      correct: 1,
      explanation: '$E_{kin,max} = h \\cdot f - W_A$. Die Energie hängt von $f$ ab — klassisch würde Intensität zählen.',
    },
    {
      id: 'qq2',
      type: 'numeric',
      question: 'Berechne die de-Broglie-Wellenlänge für ein Elektron mit $v = 10^6\\,\\text{m}/\\text{s}$. ($h \\approx 6{,}6 \\cdot 10^{-34}\\,\\text{J} \\cdot \\text{s}$, $m_e \\approx 9{,}1 \\cdot 10^{-31}\\,\\text{kg}$)',
      answer: 0.73,
      unit: 'nm',
      tolerance: 0.1,
      hint: '$\\lambda = h/(m \\cdot v)$',
      solution: '$\\lambda = 6{,}6 \\cdot 10^{-34}/(9{,}1 \\cdot 10^{-31} \\cdot 10^6) \\approx 0{,}73\\,\\text{nm}$',
      explanation: '$\\lambda = h/(m_e \\cdot v) = h/p$. Mit $p = m \\cdot v$ ergibt sich $\\lambda \\approx 0{,}73\\,\\text{nm}$.',
    },
    {
      id: 'qq3',
      type: 'formula-select',
      question: 'Welcher Zusammenhang gilt zwischen Photonenenergie und Frequenz?',
      options: ['$E = h \\cdot f$', '$E = f/h$', '$E = h/f$', '$E = h + f$'],
      correct: 0,
      explanation: 'Die Photonenenergie ist $E = h \\cdot f$ mit dem Planckschen Wirkungsquantum $h$.',
    },
    {
      id: 'qq4',
      type: 'multiple-choice',
      question: 'Warum erscheint beim Doppelspalt mit einzelnen Photonen trotzdem ein Interferenzmuster?',
      options: ['Die Photonen teilen sich', 'Nach vielen Einzelereignissen entsteht das Muster als Wahrscheinlichkeitsverteilung', 'Es gibt kein Muster', 'Die Spalte sind zu nah'],
      correct: 1,
      explanation: 'Stochastische Deutung: Das Intensitätsmuster ist die Nachweiswahrscheinlichkeit. Viele Einzelereignisse ergeben die Verteilung.',
    },
    {
      id: 'qq5',
      type: 'multiple-choice',
      question: 'Wovon ist die Nachweiswahrscheinlichkeit im Zeigermodell proportional?',
      options: ['Zeigerlänge', '(Zeigerlänge)²', '1/Zeigerlänge', 'Zeigerlänge + Konstante'],
      correct: 1,
      explanation: 'Die Nachweiswahrscheinlichkeit ist proportional zum Quadrat der Zeigerlänge: $P \\propto |\\text{Zeiger}|^2$.',
    },
    {
      id: 'qq6',
      type: 'multiple-choice',
      question: 'Was bedeutet Komplementarität? Nenne ein Beispiel.',
      options: ['Energie und Impuls sind komplementär', 'Weginformation und Interferenz schließen einander aus (Welcher-Weg-Experiment)', 'Ort und Zeit', 'Ladung und Masse'],
      correct: 1,
      explanation: 'Komplementarität: Bestimmt man den Weg (Welcher-Weg), verschwindet das Interferenzmuster. Beides gleichzeitig ist unmöglich.',
    },
    {
      id: 'qq7',
      type: 'multiple-choice',
      question: 'Unschärferelation: Wenn Δx kleiner wird, was passiert mit Δp?',
      options: ['$\\Delta p$ bleibt gleich', '$\\Delta p$ wird größer', '$\\Delta p$ wird kleiner', '$\\Delta p$ verschwindet'],
      correct: 1,
      explanation: '$\\Delta x \\cdot \\Delta p \\geq \\hbar/2$. Je genauer der Ort, desto unschärfer der Impuls.',
    },
    {
      id: 'qq8',
      type: 'formula-select',
      question: 'Beim Röntgenbremsspektrum: Wie hängt f_max mit der Anodenspannung zusammen?',
      options: ['$f_{max} = h/(e \\cdot U_A)$', '$f_{max} = e \\cdot U_A/h$', '$f_{max} = e \\cdot U_A$', '$f_{max} = h \\cdot U_A$'],
      correct: 1,
      explanation: '$E = e \\cdot U_A = h \\cdot f_{max}$. Also $f_{max} = e \\cdot U_A/h$.',
    },
    {
      id: 'qq9',
      type: 'formula-select',
      question: 'Wie lautet die de-Broglie-Wellenlänge?',
      options: ['$\\lambda = h/p$', '$\\lambda = p/h$', '$\\lambda = h \\cdot p$', '$\\lambda = m \\cdot v/h$'],
      correct: 0,
      explanation: 'Die de-Broglie-Wellenlänge ist $\\lambda = h/p = h/(m \\cdot v)$.',
    },
    {
      id: 'qq10',
      type: 'formula-select',
      question: 'Wie lautet die Heisenbergsche Unschärferelation?',
      options: ['$\\Delta x \\cdot \\Delta p = 0$', '$\\Delta x \\cdot \\Delta p \\geq h/(4\\pi)$', '$\\Delta x \\cdot \\Delta p \\leq h$', '$\\Delta x + \\Delta p \\geq h$'],
      correct: 1,
      explanation: '$\\Delta x \\cdot \\Delta p \\geq h/(4\\pi) = \\hbar/2$. Das Produkt kann nicht beliebig klein werden.',
    },
    {
      id: 'qq11',
      type: 'multiple-choice',
      question: 'Was ist die de-Broglie-Hypothese kurz formuliert?',
      options: ['Materie kann nur als Welle beschrieben werden', 'Materie hat Welleneigenschaften; $\\lambda = h/p$', 'Licht ist nur Teilchen', 'Wellen haben keine Impuls'],
      correct: 1,
      explanation: 'De Broglie: Jedem Teilchen mit Impuls $p$ kann eine Wellenlänge $\\lambda = h/p$ zugeordnet werden.',
    },
    {
      id: 'qq12',
      type: 'multiple-choice',
      question: 'Welche Aussage trifft auf das Röntgenbremsspektrum zu?',
      options: ['$f_{max}$ hängt von der Röhrentemperatur ab', '$f_{max} = e \\cdot U_A/h$ — alle Photonenenergien bis $h \\cdot f_{max}$ möglich', '$f_{max}$ ist konstant für alle Anodenspannungen', 'Es gibt keine Grenzfrequenz'],
      correct: 1,
      explanation: 'Die maximale Photonenenergie entspricht der gesamten kinetischen Energie: $h \\cdot f_{max} = e \\cdot U_A$.',
    },
    {
      id: 'qq13',
      type: 'drag-drop',
      question: 'Ordne die Größen den Quantenphänomenen zu.',
      items: ['$E = h \\cdot f$', '$\\lambda = h/p$', '$\\Delta x \\cdot \\Delta p \\geq \\hbar/2$', '$E_{kin} = e \\cdot U_A$'],
      targets: ['Photonenenergie', 'De-Broglie-Wellenlänge', 'Heisenberg-Unschärfe', 'Elektron nach Beschleunigung'],
      correctPairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Photonenenergie, de-Broglie, Unschärferelation, kinetische Energie nach Beschleunigung.',
    },
    {
      id: 'qq14',
      type: 'sort',
      question: 'Ordne die historischen Erkenntnisse (älteste → neueste).',
      items: ['Photoeffekt (Einstein)', 'Bohrsches Atommodell', 'De-Broglie-Wellen', 'Unschärferelation'],
      correctOrder: [0, 1, 2, 3],
      explanation: 'Photoeffekt 1905, Bohr 1913, de Broglie 1924, Heisenberg 1927.',
    },
    {
      id: 'qq15',
      type: 'numeric',
      question: 'Ein Photon hat $\\lambda = 500\\,\\text{nm}$. Berechne die Energie in eV. ($h \\cdot c \\approx 1240\\,\\text{eV} \\cdot \\text{nm}$)',
      answer: 2.48,
      unit: 'eV',
      tolerance: 0.05,
      hint: '$E = h \\cdot c/\\lambda$',
      solution: '$E = 1240/500 \\approx 2{,}48\\,\\text{eV}$',
      explanation: '$E = hc/\\lambda$. Mit $hc \\approx 1240\\,\\text{eV} \\cdot \\text{nm}$: $E = 1240/500 \\approx 2{,}48\\,\\text{eV}$.',
    },
  ],

  // ========== MODUL 4: ATOMHÜLLE & ATOMKERN ==========
  'atomhuelle/atomhuelle-kapitel': [
    {
      id: 'ah1',
      type: 'numeric',
      question: 'Welche Energie hat der Grundzustand ($n=1$) im Potenzialtopf mit $L = 0{,}1\\,\\text{nm}$? ($h = 6{,}6 \\cdot 10^{-34}\\,\\text{J} \\cdot \\text{s}$, $m_e = 9{,}1 \\cdot 10^{-31}\\,\\text{kg}$)',
      answer: 37.5,
      unit: 'eV',
      tolerance: 0.15,
      hint: '$E_n = h^2/(8m_e L^2) \\cdot n^2$',
      solution: '$E_1 = h^2/(8m_e L^2) \\approx 6 \\cdot 10^{-18}\\,\\text{J} \\approx 37{,}5\\,\\text{eV}$',
      explanation: '$E_1 = h^2/(8 \\cdot m_e \\cdot L^2) \\cdot 1^2$. Mit $L = 10^{-10}\\,\\text{m}$ ergibt sich etwa $37{,}5\\,\\text{eV}$.',
    },
    {
      id: 'ah2',
      type: 'formula-select',
      question: 'Wie lautet die Energieformel im eindimensionalen Potenzialtopf?',
      options: ['$E_n = h^2/(8m_e L^2) \\cdot n^2$', '$E_n = n \\cdot h \\cdot f$', '$E_n = m_e \\cdot c^2$', '$E_n = h/(2\\pi) \\cdot n$'],
      correct: 0,
      explanation: '$E_n = h^2/(8 \\cdot m_e \\cdot L^2) \\cdot n^2$ für $n = 1, 2, 3, \\ldots$',
    },
    {
      id: 'ah3',
      type: 'multiple-choice',
      question: 'Franck-Hertz: Was bedeuten die regelmäßigen Einbrüche der Kennlinie?',
      options: ['Kathodenverschleiß', 'Anregung der Atome bei der Anregungsenergie', 'Kondensation', 'Spannungsabfall'],
      correct: 1,
      explanation: 'Die Einbrüche liegen im Abstand der Anregungsenergie (z.B. 4,9 eV bei Quecksilber).',
    },
    {
      id: 'ah4',
      type: 'formula-select',
      question: 'Wie hängt die Wellenlänge einer Spektrallinie mit ΔE zusammen?',
      options: ['$\\Delta E = \\lambda/(hc)$', '$\\Delta E = hc/\\lambda$', '$\\Delta E = \\lambda \\cdot hc$', '$\\Delta E = h/\\lambda$'],
      correct: 1,
      explanation: '$\\Delta E = h \\cdot f = hc/\\lambda$. Also $\\lambda = hc/\\Delta E$.',
    },
    {
      id: 'ah5',
      type: 'multiple-choice',
      question: 'Was ist Besetzungsinversion und warum braucht man sie für den Laser?',
      options: ['Alle Atome im Grundzustand', 'Mehr Atome im oberen als im unteren Niveau — nötig für stimulierte Emission', 'Gleich viele in allen Niveaus', 'Keine Anregung'],
      correct: 1,
      explanation: 'Besetzungsinversion: Mehr angeregt als im Grundzustand. Nur so überwiegt stimulierte Emission die Absorption.',
    },
    {
      id: 'ah6',
      type: 'numeric',
      question: 'Welche Wellenlänge hat der Übergang Hα ($n=3 \\to 2$) nach Balmer? ($R \\approx 1{,}1 \\cdot 10^7\\,\\text{m}^{-1}$)',
      answer: 656,
      unit: 'nm',
      tolerance: 0.05,
      hint: '$1/\\lambda = R \\cdot (1/4 - 1/9)$',
      solution: '$1/\\lambda = R \\cdot 5/36 \\to \\lambda \\approx 656\\,\\text{nm}$',
      explanation: 'Balmer: $1/\\lambda = R \\cdot (1/2^2 - 1/3^2) = R \\cdot 5/36$. $\\lambda \\approx 656\\,\\text{nm}$.',
    },
    {
      id: 'ah7',
      type: 'drag-drop',
      question: 'Ordne die Wasserstoff-Serien ihren Endniveaus zu.',
      items: ['Lyman-Serie', 'Balmer-Serie', 'Paschen-Serie'],
      targets: ['n = 1 (UV)', 'n = 2 (sichtbar)', 'n = 3 (Infrarot)'],
      correctPairs: [[0, 0], [1, 1], [2, 2]],
      explanation: 'Lyman → n=1 (UV), Balmer → n=2 (sichtbar), Paschen → n=3 (IR).',
    },
    {
      id: 'ah8',
      type: 'sort',
      question: 'Ordne die Linienserien nach Energie (höchste → niedrigste).',
      items: ['Lyman (UV)', 'Balmer (sichtbar)', 'Paschen (IR)'],
      correctOrder: [0, 1, 2],
      explanation: 'Lyman hat höchste Energie (Übergang nach n=1), Paschen niedrigste (n=3).',
    },
  ],
  'atomhuelle/atomkern': [
    {
      id: 'ak1',
      type: 'multiple-choice',
      question: 'Welche Strahlungsart besteht aus Heliumkernen?',
      options: ['Beta', 'Alpha', 'Gamma', 'Röntgen'],
      correct: 1,
      explanation: 'Alpha-Strahlung = Heliumkerne ($^4\\text{He}^{2+}$).',
    },
    {
      id: 'ak2',
      type: 'numeric',
      question: 'Berechne $T_{1/2}$ für $\\lambda = 0{,}001\\,\\text{s}^{-1}$.',
      answer: 693,
      unit: 's',
      tolerance: 0.05,
      hint: '$T_{1/2} = \\ln(2)/\\lambda$',
      solution: '$T_{1/2} = 0{,}693/0{,}001 = 693\\,\\text{s}$',
      explanation: '$T_{1/2} = \\ln(2)/\\lambda \\approx 0{,}693/\\lambda = 693\\,\\text{s}$.',
    },
    {
      id: 'ak3',
      type: 'formula-select',
      question: 'Wie hängen Halbwertszeit T½ und Zerfallskonstante λ zusammen?',
      options: ['$T_{1/2} = \\lambda \\cdot \\ln(2)$', '$T_{1/2} = \\ln(2)/\\lambda$', '$T_{1/2} = \\lambda/2$', '$T_{1/2} = 1/\\lambda$'],
      correct: 1,
      explanation: '$T_{1/2} = \\ln(2)/\\lambda \\approx 0{,}693/\\lambda$.',
    },
    {
      id: 'ak4',
      type: 'multiple-choice',
      question: 'Wie ändern sich Z und A beim α-Zerfall?',
      options: ['Z −2, A −4', 'Z +1, A gleich', 'Z −1, A gleich', 'Z +2, A +4'],
      correct: 0,
      explanation: 'Beim α-Zerfall werden 2 Protonen und 2 Neutronen abgegeben.',
    },
    {
      id: 'ak5',
      type: 'multiple-choice',
      question: 'C14-Methode: Warum kann man damit nicht unbegrenzt weit in die Vergangenheit?',
      options: ['C14 ist zu teuer', 'Nach etwa 10 Halbwertszeiten ist zu wenig C14 nachweisbar', 'C14 existiert nicht', 'Die Methode ist zu ungenau'],
      correct: 1,
      explanation: 'T½ ≈ 5730 a. Nach ~50.000 Jahren ist so wenig C14 übrig, dass die Messung ungenau wird.',
    },
    {
      id: 'ak6',
      type: 'multiple-choice',
      question: 'Was zeigt die Bragg-Kurve und warum ist sie in der Strahlentherapie wichtig?',
      options: ['Energieabgabe vs. Eindringtiefe; Dosis gezielt im Tumor', 'Zerfallsrate; für Halbwertszeit', 'Ionisation; für GMZ', 'Reichweite; für Abschirmung'],
      correct: 0,
      explanation: 'Die Bragg-Kurve zeigt die Energieabgabe. Der Bragg-Peak erlaubt gezielte Tumorbestrahlung bei minimaler Schädigung dahinter.',
    },
    {
      id: 'ak7',
      type: 'drag-drop',
      question: 'Ordne die Strahlungsarten ihren Eigenschaften zu.',
      items: ['Alpha', 'Beta', 'Gamma'],
      targets: ['Heliumkern, geringe Reichweite', 'Elektron/Positron, mittlere Reichweite', 'Photon, große Reichweite'],
      correctPairs: [[0, 0], [1, 1], [2, 2]],
      explanation: 'α: Heliumkerne, wenig Reichweite. β: Elektronen. γ: Photonen, durchdringend.',
    },
    {
      id: 'ak8',
      type: 'formula-select',
      question: 'Wie lautet das Zerfallsgesetz?',
      options: ['$N(t) = N_0 \\cdot e^{-\\lambda t}$', '$N(t) = N_0 \\cdot \\lambda \\cdot t$', '$N(t) = N_0/\\lambda$', '$N(t) = N_0 + \\lambda t$'],
      correct: 0,
      explanation: '$N(t) = N_0 \\cdot e^{-\\lambda t}$. Exponentieller Abfall.',
    },
  ],

  // ========== MODUL 5: MESSUNSICHERHEITEN ==========
  'messunsicherheiten/messunsicherheiten-kapitel': [
    {
      id: 'mu1',
      type: 'multiple-choice',
      question: '$s = 70\\,\\text{mm}$. Wie viele signifikante Stellen hat die Messung? Mit wie vielen Stellen gibt man das Ergebnis an?',
      options: ['2 Stellen; 2 Stellen', '2 Stellen; 3 Stellen', '3 Stellen; 3 Stellen', '1 Stelle; 2 Stellen'],
      correct: 1,
      explanation: '70 mm hat 2 signifikante Stellen. Ergebnis mit (n+1) = 3 Stellen angeben.',
    },
    {
      id: 'mu2',
      type: 'numeric',
      question: 'Berechne die relative Unsicherheit für $\\Delta s/s = 1/70$ (in Prozent, gerundet).',
      answer: 1.43,
      unit: '%',
      tolerance: 0.1,
      hint: '$1/70 \\cdot 100$',
      solution: '$1/70 \\approx 0{,}0143 = 1{,}43\\,\\%$',
      explanation: '$\\Delta s/s = 1/70 \\approx 0{,}0143 = 1{,}43\\,\\%$.',
    },
    {
      id: 'mu3',
      type: 'multiple-choice',
      question: 'Welche Eingangsgröße bestimmt die Gesamtunsicherheit — und warum?',
      options: ['Die größte', 'Die mit der größten relativen Unsicherheit (schwächstes Glied)', 'Die erste', 'Die kleinste'],
      correct: 1,
      explanation: 'Das schwächste Glied (größte relative Unsicherheit) dominiert die Gesamtunsicherheit.',
    },
    {
      id: 'mu4',
      type: 'multiple-choice',
      question: 'Mit wie vielen signifikanten Stellen gibt man die absolute Unsicherheit des Ergebnisses an?',
      options: ['1 Stelle', '2 Stellen', '3 Stellen', 'So viele wie der Rechner'],
      correct: 1,
      explanation: 'Die absolute Unsicherheit wird stets mit 2 signifikanten Stellen angegeben.',
    },
    {
      id: 'mu5',
      type: 'multiple-choice',
      question: 'Unterschied: absolute vs. relative Unsicherheit?',
      options: ['Kein Unterschied', '$\\Delta x$ hat Einheit der Messgröße; $\\Delta x/x$ ist dimensionslos (oft %)', '$\\Delta x/x$ hat Einheit; $\\Delta x$ nicht', 'Beide sind gleich'],
      correct: 1,
      explanation: 'Absolute Unsicherheit $\\Delta x$ hat die gleiche Einheit wie $x$. Relative Unsicherheit $\\Delta x/x$ ist dimensionslos.',
    },
    {
      id: 'mu6',
      type: 'formula-select',
      question: 'Wie lautet die relative Unsicherheit?',
      options: ['$\\Delta x \\cdot x$', '$\\Delta x/x$', '$x/\\Delta x$', '$\\Delta x + x$'],
      correct: 1,
      explanation: 'Die relative Unsicherheit ist $\\Delta x/x$ (dimensionslos, oft in %).',
    },
    {
      id: 'mu7',
      type: 'multiple-choice',
      question: 'Wie viele signifikante Stellen hat die Zahl 70 mm?',
      options: ['1', '2', '3', 'Unendlich viele'],
      correct: 1,
      explanation: '$70\\,\\text{mm}$ hat 2 signifikante Stellen. $70{,}0\\,\\text{mm}$ hätte 3.',
    },
    {
      id: 'mu8',
      type: 'drag-drop',
      question: 'Ordne die Unsicherheitsquellen den Begriffen zu.',
      items: ['Ablesefehler', 'Herstellerangabe', 'Digitalisierung', 'Schwächstes Glied'],
      targets: ['± halbe Skalenteilung', '± x% vom Messwert', '± letzte Stelle', 'Größte relative Unsicherheit dominiert'],
      correctPairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Ablesefehler, Herstellerangabe, Digitalisierung, schwächstes Glied.',
    },
    {
      id: 'mu9',
      type: 'numeric',
      question: 'Eine Messung ergibt x = 12,3 cm mit Δx = 0,15 cm. Berechne die relative Unsicherheit in Prozent.',
      answer: 1.22,
      unit: '%',
      tolerance: 0.1,
      hint: '$(\\Delta x/x) \\cdot 100$',
      solution: '$(0{,}15/12{,}3) \\cdot 100 \\approx 1{,}22\\,\\%$',
      explanation: 'Relative Unsicherheit: $\\Delta x/x = 0{,}15/12{,}3 \\approx 0{,}0122 = 1{,}22\\,\\%$.',
    },
    {
      id: 'mu10',
      type: 'multiple-choice',
      question: 'Warum rundet man die absolute Unsicherheit auf 2 signifikante Stellen?',
      options: ['Konvention', 'Genaue Kenntnis darüber hinaus ist physikalisch nicht sinnvoll', 'Rechenvorteil', 'Weil Messgeräte so geeicht sind'],
      correct: 1,
      explanation: 'Weitere Stellen wären präziser als die Messung selbst — die Unsicherheit ist selbst unsicher.',
    },
    {
      id: 'mu11',
      type: 'formula-select',
      question: 'Wie lautet die Fehlerfortpflanzung bei Addition zweier Größen?',
      options: ['$\\Delta(x+y) = \\Delta x + \\Delta y$', '$\\Delta(x+y) = \\sqrt{\\Delta x^2 + \\Delta y^2}$', '$\\Delta(x+y) = \\Delta x \\cdot \\Delta y$', '$\\Delta(x+y) = (\\Delta x + \\Delta y)/2$'],
      correct: 0,
      explanation: 'Bei Addition: $\\Delta(x+y) = \\Delta x + \\Delta y$. Bei unkorrelierten Fehlern: oft $\\Delta z = \\sqrt{\\Delta x^2 + \\Delta y^2}$ für $z = f(x,y)$.',
    },
    {
      id: 'mu12',
      type: 'multiple-choice',
      question: 'Warum ist die relative Unsicherheit beim Multiplizieren/Dividieren oft nützlicher?',
      options: ['Sie ist immer kleiner', 'Relative Unsicherheiten addieren sich bei Produkt/Quotient', 'Absolute Unsicherheiten gibt es nicht', 'Sie hat keine Einheit'],
      correct: 1,
      explanation: 'Bei $y = x_1 \\cdot x_2/\\ldots$ addieren sich die relativen Unsicherheiten: $\\Delta y/y \\approx \\Delta x_1/x_1 + \\Delta x_2/x_2 + \\ldots$',
    },
    {
      id: 'mu13',
      type: 'sort',
      question: 'Ordne die Schritte einer fehlerbehafteten Auswertung.',
      items: ['Ergebnis mit Unsicherheit angeben', 'Messwerte erfassen', 'Unsicherheiten der Eingangsgrößen abschätzen', 'Fehlerfortpflanzung durchführen'],
      correctOrder: [1, 2, 3, 0],
      explanation: 'Messung → Unsicherheiten abschätzen → Fortpflanzung → Ergebnis angeben.',
    },
    {
      id: 'mu14',
      type: 'numeric',
      question: '$z = x \\cdot y$ mit $x = 10 \\pm 1$, $y = 5 \\pm 0{,}5$. Schätze die relative Unsicherheit von $z$ (in %).',
      answer: 20,
      unit: '%',
      tolerance: 0.5,
      hint: 'Δz/z ≈ Δx/x + Δy/y',
      solution: '1/10 + 0,5/5 = 0,1 + 0,1 = 0,2 = 20 %',
      explanation: 'Δz/z ≈ Δx/x + Δy/y = 0,1 + 0,1 = 20 %. Für grobe Schätzung: ~15–20 %.',
    },
    {
      id: 'mu15',
      type: 'multiple-choice',
      question: 'Was bedeutet „systematischer Fehler“ im Gegensatz zu „zufälligem Fehler“?',
      options: ['Beide sind gleich', 'Systematisch: konstant, reproduzierbar; Zufällig: streut um Mittelwert', 'Zufällig ist größer', 'Systematisch verschwindet beim Mittelwert'],
      correct: 1,
      explanation: 'Systematisch: z.B. falsche Eichung, immer in eine Richtung. Zufällig: Ableseungenauigkeit, streut.',
    },
  ],
};

export function getQuizQuestions(moduleId: string, chapterSlug: string): QuizQuestion[] {
  const key: QuizKey = `${moduleId}/${chapterSlug}`;
  return quizQuestionsMap[key] ?? [];
}
